# Paramètres de base
crawl:
  user_agent: "SemanticClusterBot/0.1 (+https://example.com)"
  max_pages: 200
  max_depth: 2
  same_domain_only: true
  request_delay_seconds: 1.0

nlp:
  language: "fr"
  spacy_model: "fr_core_news_lg"
  top_ngrams: 40
  ngram_range: [1,3]
  max_features_tfidf: 12000

similarity:
  model_name: "paraphrase-multilingual-MiniLM-L12-v2"
  top_k: 6
  intra_cluster_threshold: 0.38

linking:
  intra_cluster_topk: 5
  cross_cluster_topk: 2

briefs:
  per_page_terms: 30
  essential_ratio: 0.4
  secondary_ratio: 0.4
  opportunity_ratio: 0.2

briefs_pro:
  per_page_terms: 40
  target_len_words: 1200

serp:
  provider: "google"
  topn: 5
